imports:
    - { resource: admin.yml }

# Doctrine Configuration
doctrine:
    dbal:
        types:
            json: Sonata\Doctrine\Types\JsonType
            gender: Siciarek\LeaveManagementBundle\Doctrine\DBAL\Types\GenderType
            leave: Siciarek\LeaveManagementBundle\Doctrine\DBAL\Types\LeaveType
            leave_status: Siciarek\LeaveManagementBundle\Doctrine\DBAL\Types\LeaveStatusType
        mapping_types:
            enum: string
            set: string
            varbinary: string
            tinyblob: text
    orm:
        entity_managers:
            default:
                mappings:
                    SiciarekLeaveManagementBundle: ~
