Siciarek\LeaveManagementBundle\Entity\Employee:
    type: entity
    table: slm_employee
    repositoryClass: EmployeeRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        first_name: ~
        last_name: ~
        email: ~
        is_manager:
            type: boolean
        enabled:
            type: boolean
        attributable_leave_days_number:
            type: smallint
        slug:
            type: string
            length: 128
            gedmo:
                slug:
                    fields:
                        - first_name
                        - last_name
        created_at:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updated_at:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        deleted_at:
            type: datetime
            nullable: true

    manyToOne:
        manager:
            targetEntity: Employee

