Siciarek\LeaveManagementBundle\Entity\Leave:
    type: entity
    table: slm_leave
    repositoryClass: LeaveRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:

        type:
            type: leave

        status:
            type: leave_status

        starts_at:
            type: date

        ends_at:
            type: date

        length:
            type: smallint

        working_days:
            type: smallint

        description:
            length: 255
            nullable: true

        created_at:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updated_at:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        deleted_at:
            type: datetime
            nullable: true

    manyToOne:
        employee:
            targetEntity: Employee
        covered_by:
            targetEntity: Employee
        approved_by:
            targetEntity: Employee
        canceled_by:
            targetEntity: Employee
